#!/usr/bin/env bash

# Get the settings variables
source /autograder/GradescopeDeploymentAutograder/settings.sh

# Update autograder files
cd $AGROOT
git pull origin $BRANCH
git submodule update --init --recursive
# Make sure the run_autograder script is runnable
chmod +x run_autograder

# Execute (source) the run autograder script from the same location.
./run_autograder
